# Generated by Django 2.2.4 on 2021-03-02 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_alternativa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alternativa')),
                ('emoji', models.CharField(blank=True, max_length=100, null=True, verbose_name='Emoji')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
                'ordering': ['nome_alternativa'],
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_votos', models.IntegerField(blank=True, default=0, null=True)),
                ('data_voto', models.DateField(auto_now=True)),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.Alternativa')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
            },
        ),
        migrations.CreateModel(
            name='Enquente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquete_texto', models.TextField(max_length=500, verbose_name='Enquete')),
                ('isAtiva', models.BooleanField(default=True, verbose_name='Enquete Ativa')),
                ('data_enquete', models.DateField(auto_now_add=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.Estabelecimento')),
            ],
            options={
                'verbose_name': 'Enquete',
                'verbose_name_plural': 'Enquetes',
                'ordering': ['-data_enquete'],
            },
        ),
        migrations.AddField(
            model_name='alternativa',
            name='enquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.Enquente'),
        ),
    ]
