# Generated by Django 2.2.4 on 2021-02-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliacao_cliente',
            field=models.CharField(choices=[['Ruim', 'Ruim'], ['Normal', 'Normal'], ['Bom', 'Bom']], max_length=25),
        ),
    ]
